services:
  - docker

before_install:
  - docker build --tag roblobob/03-multi-container-deploy-test -f ./client/Dockerfile.dev ./client

script:
  - docker run --env CI=true roblobob/03-multi-container-deploy-test npm run test

after_success:
  - docker build --tag roblobob/03-multi-container-deploy-client ./client
  - docker build --tag roblobob/03-multi-container-deploy-router ./nginx
  - docker build --tag roblobob/03-multi-container-deploy-server ./server
  - docker build --tag roblobob/03-multi-container-deploy-worker ./worker
  # login to docker cli and push images
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push roblobob/03-multi-container-deploy-client
  - docker push roblobob/03-multi-container-deploy-router
  - docker push roblobob/03-multi-container-deploy-server
  - docker push roblobob/03-multi-container-deploy-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: 03-multi-container-deploy
  env: 03MultiContainerDeploy-env
  bucket_name: elasticbeanstalk-eu-west-2-380631270758
  bucket_path: 03-multi-container-deploy
  on:
    branch: master
  access_key_id: $AWS_ACCESS_ID
  secret_access_key:
    secure: $AWS_SECRET_KEY
